### ISSUE TITLE
Show status

### ISSUE THREAD

**Issue by LadyMadonna** [victorpimentel/TVShows#11]
Currently, TVShows only shows you if a show is cancelled after you've subscribed to, and still, you have to click the image to see that. It could be nice to show this information along with the synopsis of the show in the "add show" window so you can see it before subscribing.

Also, there could be an icon over the show image in the subscriptions view (like the "HD" one) that displays the show status (for example, red dot = cancelled or ended, green dot = continuing).

**Comment by victorpimentel** [comment]
We have to think a little about one thing: what is the goal of TVShows? If the goal is to only download new torrents, then it is not really helpful to have ended shows hanging around in the show list.

So the real solution should be to not add those ended shows. Since we obtain the shows from parsing [this page](http://showrss.karmorra.info/?cs=feeds), we could ask ShowRSS to clean the show list or have an additional page. I have to talk with them anyway :)

Another solution could be to check one by one if the show has ended or not. But that could be really (really) slow since that would literally mean to download hundreds of pages of TVDB each time the dropdown is shown.

A third solution could be to write a script in my server to check every day every status show. Then that file could be downloaded from the application. Basically ShowRSS would not be checked anymore (only their RSS), so it would add a little load to my server. The advantage of this is that I control what the script does, the disadvantage is that my server could be slow or down, adding another point of failure. But, I don't know, maybe I can automatically check that file to a GitHub repository every night and then the app could check that (and my server as a mirror).

The only unanswered question is what to do with current subscriptions when the show ends. It could be automatically removed when detected., maybe with a notification to the user.

Anyway, in any case it does not make sense to me to add this now. I do not think that the correct evolution of TVShows is to be a downloader of ended shows. There are better solutions to that problem and wasting our attention will diverge us from the real point of the application. For me, the only cases where the download buttons near the episode names are needed are to download an episode TVShows missed/failed or when in a new subscription to download a previous episode the user didn't see. Those are really specific problems, and always to one episode.
