### ISSUE TITLE
Add compat with new x264 naming and encoding scheme

### ISSUE THREAD

**Issue by MaDDoGo** [victorpimentel/TVShows#37]
Hi,

from last week a few scene groups agreed in having a new standard for tvshows (480p), encoding in x264 & mp4 container. Because of this new rule there are some new shows that doesn't download well. For example,

http://eztv.it/ep/33428/the-big-bang-theory-s05e18-hdtv-x264-lol/
http://eztv.it/ep/33435/greys-anatomy-s08e16-hdtv-x264-lol/

Think that this is doable with a simple change in regex from whatever it is now to x264+hdtv (480p), 720p or 1080i to change between formats, don't you think?

Cheers!

**Comment by dustinrue** [comment]
I'm interested in this one as well, I'm not getting what I'd call HD material anymore

**Comment by Pipen** [comment]
I agree with the original post, but looking at the commit https://github.com/victorpimentel/TVShows/commit/d7d1ba5dae6b473789ea8f34b925033891b05fb9 this seems to already be solved. Only titles containing 720 or 1080 will be downloaded as HD material.

I can't comment on how it works, because the last version is unusable for me for other reasons.
