### ISSUE TITLE
Adding MagneticTorrent support

### ISSUE THREAD

**Issue by weldyss** [victorpimentel/TVShows#48]
How many chances to add magnetic torrent support to TVShows? I'm using and how I don't know anything about that, I bring this question :\

I could fork to add, but... :(

**Comment by LadyMadonna** [comment]
uhm... have you checked the Preferences tab? There's an option called "Prioritize magnet links".

**Comment by weldyss** [comment]
Yep, but doesn't working. I guessed a anyone problem about that support :\

**Comment by LadyMadonna** [comment]
What do you mean it isn't working? Lots of users (me included) are using that feature and it works for us. Maybe there's something wrong with your setup, explaining how "it doesn't work" for you could help us figure out what. Please open a ticket at our [support page](http://support.tvshowsapp.com), include the log (About tab -> View logs, please paste it into a text file and attach it to the message) and explain some details, like: does it automatically download anything? Do you see episodes in the list? What happens when you try to manually download them?
